[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "nutrisage"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]          # code lives in src/
